/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Mon Apr  4 18:57:36 2016
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define T1_id 1
#define T2_id 2
#define T3_id 3
#define R1_id 4
#define R2_id 5
#define R3_id 6
#define RHipLat_id 7
#define RHipYaw_id 8
#define RHipSag_id 9
#define RKneeSag_id 10
#define RAnkSag_id 11
#define RAnkLat_id 12
#define FT_RFoot_R3_id 13
#define FT_RFoot_R2_id 14
#define FT_RFoot_R1_id 15
#define FT_RFoot_Z_id 16
#define FT_RFoot_Y_id 17
#define FT_RFoot_X_id 18
#define LHipLat_id 19
#define LHipYaw_id 20
#define LHipSag_id 21
#define LKneeSag_id 22
#define LAnkSag_id 23
#define LAnkLat_id 24
#define FT_LFoot_R3_id 25
#define FT_LFoot_R2_id 26
#define FT_LFoot_R1_id 27
#define FT_LFoot_Z_id 28
#define FT_LFoot_Y_id 29
#define FT_LFoot_X_id 30
#define WaistR2_fixed_id 31
#define WaistLat_id 32
#define WaistSag_id 33
#define WaistYaw_id 34
#define RShR2fixed_id 35
#define Joint_1_id 36
#define RShSag_id 37
#define RShLat_id 38
#define RShYaw_id 39
#define RElbj_id 40
#define RForearmPlate_id 41
#define RWrj1_id 42
#define RWrj2_id 43
#define LShR2fixed_id 44
#define Joint_0_id 45
#define LShSag_id 46
#define LShLat_id 47
#define LShYaw_id 48
#define LElbj_id 49
#define LForearmPlate_id 50
#define LWrj1_id 51
#define LWrj2_id 52
#define NeckYawj_id 53
#define NeckPitchj_id 54
#define neck_joint_id 55


// body

#define Waist_id 6
#define RHipMot_id 7
#define RThighUpLeg_id 8
#define RThighLowLeg_id 9
#define RLowLeg_id 10
#define RFootmot_id 11
#define RAnkInterface_id 12
#define RFoot_id 18
#define LHipMot_id 19
#define LThighUpLeg_id 20
#define LThighLowLeg_id 21
#define LLowLeg_id 22
#define LFootmot_id 23
#define LAnkInterface_id 24
#define LFoot_id 30
#define DWL_id 32
#define DWS_id 33
#define DWYTorso_id 34
#define RShp_id 37
#define RShr_id 38
#define RShy_id 39
#define RElb_id 40
#define RForearm_id 41
#define RWrMot2_id 42
#define RWrMot3_id 43
#define LShp_id 46
#define LShr_id 47
#define LShy_id 48
#define LElb_id 49
#define LForearm_id 50
#define LWrMot2_id 51
#define LWrMot3_id 52
#define NeckYaw_id 53
#define NeckPitch_id 54
#define head_id 55


// point

#define Point_0_id 0
#define Point_1_id 1
#define Point_2_id 2
#define Point_cg_id 3
#define Point_0_id 4
#define Point_0_id 5
#define Point_0_id 6
#define Point_0_id 7
#define Point_0_id 8
#define Point_1_id 9
#define Point_0_id 10
#define Point_0_id 11
#define Point_0_id 12
#define Point_0_id 13
#define Point_0_id 14
#define Point_0_id 15
#define Point_1_id 16
#define Point_0_id 17
#define Point_0_id 18
#define Point_cg_id 19
#define Point_0_id 20
#define Point_cg_id 21
#define Point_0_id 22
#define Point_1_id 23
#define Point_2_id 24
#define Point_cg_id 25
#define Point_0_id 26
#define Point_cg_id 27
#define Point_0_id 28
#define Point_cg_id 29
#define Point_0_id 30
#define Point_cg_id 31
#define Point_0_id 32
#define Point_cg_id 33
#define Point_0_id 34
#define Point_cg_id 35
#define Point_0_id 36
#define Point_cg_id 37
#define Point_cg_id 38
#define Point_hand_id 39
#define Point_0_id 40
#define Point_cg_id 41
#define Point_0_id 42
#define Point_cg_id 43
#define Point_1_id 44
#define Point_0_id 45
#define Point_cg_id 46
#define Point_0_id 47
#define Point_cg_id 48
#define Point_0_id 49
#define Point_cg_id 50
#define Point_0_id 51
#define Point_cg_id 52
#define Point_hand_id 53
#define Point_cg_id 54
#define Point_0_id 55
#define Point_0_id 56


// sensor

#define WaistCg_id 1
#define RFoot_sens_id 2
#define LFoot_sens_id 3
#define DWLCg_id 4
#define DWSCg_id 5
#define DWYTorsoCg_id 6
#define RShpCg_id 7
#define RShrCg_id 8
#define RShyCg_id 9
#define RElbCg_id 10
#define RFArmCg_id 11
#define RWrMot2Cg_id 12
#define RhandCg_id 13
#define Rhand_sens_id 14
#define LShpCg_id 15
#define LShrCg_id 16
#define LShyCg_id 17
#define LElbCg_id 18
#define LFArmCg_id 19
#define LWrMot2Cg_id 20
#define Lhand_sens_id 21
#define LhandCg_id 22


// extforce

#define RFoot_force_id 1
#define LFoot_force_id 2


// links



// ============================================================ //

# endif
